schemaVersion: 2.2.0
metadata:
  name: 'DO Portal_Frontend - Dev'
attributes:
  space:
    instanceType: regular
    editor:
      type: Fleet
version: '1.0'
services:
  backend:
    image: node:18
    environment:
      NODE_ENV: dev
      PORT: 4200
      FIREBASE_PROJECT_ID: your_project_id
      FIREBASE_API_KEY: your_api_key
      FIREBASE_AUTH_DOMAIN: your_auth_domain
      FIREBASE_DATABASE_URL: your_database_url
      FIREBASE_STORAGE_BUCKET: your_storage_bucket
      FIREBASE_MESSAGING_SENDER_ID: your_sender_id
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - .:/app
    command: npm run start:dev